# Generated by Django 3.2 on 2022-06-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_links_links_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('timestamp', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
    ]
