# Generated by Django 3.2 on 2022-06-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20220611_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='link',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
